### PR TITLE
Relax dependencies

### PR DESCRIPTION
**Pull request by sjperkins**
- [x] Tests added / passed

  ```bash
  $ py.test -v -s africanus
  ```

  If the pre-commit tests fail, install and
  run the pre-commit hooks in your development
  virtuale environment:

  ```bash
  $ pip install pre-commit
  $ pre-commit install
  $ pre-commit run -a
  ```

- [x] Fully documented, including `HISTORY.rst` for all changes
      and one of the `docs/*-api.rst` files for new API

  To build the docs locally:

  ```bash
  pip install -r requirements.readthedocs.txt
  cd docs
  READTHEDOCS=True make html
  ```

----
📚 Documentation preview 📚: https://codex-africanus--324.org.readthedocs.build/en/324/

### CODE REVIEW

**Comment by sjperkins** [comment]
In #322, most codex dependencies were upgraded to fairly recent versions.

This PR relaxes the dask and numpy requirements somewhat, but numba remains at 0.60, mostly because there's a numpy >= 2 dependency.

Pinging @landmanbester @JSKenyon for review here as these upgrades might be aggressive for Quartical and pfb-imaging.

**Review by landmanbester — APPROVED** [review]
All good on my side, happy with the upgrades

**Review by JSKenyon — APPROVED** [review]
QuartiCal has bracketed dependencies so this won't break it. I will do a QuartiCal release at some point to update to this version and iron out any bugs (but the tests already pass).

**Comment by sjperkins** [comment]
Thanks for taking a look

**Pull request merged**
